services:
  sentimeter-ollama:
    image: "docker.io/ollama/ollama:0.6.8"
    ports:
      - "8000:11434"
    volumes:
      - type: "volume"
        target: "/root/.ollama"
        source: "sentimeter-ollama-data"
        read_only: false
    networks:
      - "aspire"
  sentimeter-postgres:
    image: "docker.io/library/postgres:17.4"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${SENTIMETER_POSTGRES_PASSWORD}"
    ports:
      - "8001:5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "sentimeter-postgres-data"
        read_only: false
    networks:
      - "aspire"
  sentimeter-identity:
    image: "quay.io/keycloak/keycloak:26.2"
    command:
      - "start"
      - "--import-realm"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${SENTIMETER_IDENTITY_PASSWORD}"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "9999:8080"
      - "8002:9000"
    volumes:
      - type: "volume"
        target: "/opt/keycloak/data"
        source: "sentimeter-identity-data"
        read_only: false
      - type: "bind"
        target: "/opt/keycloak/data/import"
        source: "C:\\Dev\\Education\\sentimeter\\src\\Sentimeter.AppHost\\Realms"
        read_only: false
    networks:
      - "aspire"
  messaging:
    image: "docker.io/library/rabbitmq:4.1-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${MESSAGING_PASSWORD}"
    ports:
      - "8003:5672"
      - "8004:15672"
    networks:
      - "aspire"
  sentimeter-webapi:
    image: "${SENTIMETER_WEBAPI_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8005"
      services__sentimeter-identity__http__0: "http://sentimeter-identity:8080"
      services__sentimeter-identity__management__0: "http://sentimeter-identity:9000"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      ConnectionStrings__sentimeter-db: "Host=sentimeter-postgres;Port=5432;Username=postgres;Password=${SENTIMETER_POSTGRES_PASSWORD};Database=sentimeter-db"
      YOUTUBE_APIKEY: "${YOUTUBEAPIKEY}"
    ports:
      - "8006:8005"
      - "8008:8007"
    depends_on:
      sentimeter-identity:
        condition: "service_started"
      sentimeter-postgres:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  sentimeter-webapp:
    image: "${SENTIMETER_WEBAPP_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8009"
      services__sentimeter-webapi__http__0: "http://sentimeter-webapi:8005"
      services__sentimeter-identity__http__0: "http://sentimeter-identity:8080"
      services__sentimeter-identity__management__0: "http://sentimeter-identity:9000"
    ports:
      - "8010:8009"
      - "8012:8011"
    depends_on:
      sentimeter-webapi:
        condition: "service_started"
    networks:
      - "aspire"
  sentimeter-analysis-worker:
    image: "${SENTIMETER_ANALYSIS_WORKER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__sentimeter-llama3: "Endpoint=http://sentimeter-ollama:11434;Model=llama3.2:3b"
      ConnectionStrings__sentimeter-db: "Host=sentimeter-postgres;Port=5432;Username=postgres;Password=${SENTIMETER_POSTGRES_PASSWORD};Database=sentimeter-db"
    depends_on:
      sentimeter-ollama:
        condition: "service_started"
      sentimeter-postgres:
        condition: "service_started"
    networks:
      - "aspire"
  sentimeter-dataretrieval-worker:
    image: "${SENTIMETER_DATARETRIEVAL_WORKER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__sentimeter-db: "Host=sentimeter-postgres;Port=5432;Username=postgres;Password=${SENTIMETER_POSTGRES_PASSWORD};Database=sentimeter-db"
      ConnectionStrings__messaging: "amqp://guest:${MESSAGING_PASSWORD}@messaging:5672"
      YOUTUBE_APIKEY: "${YOUTUBEAPIKEY}"
    depends_on:
      sentimeter-postgres:
        condition: "service_started"
      messaging:
        condition: "service_started"
    networks:
      - "aspire"
  sentimeter-support-migration-worker:
    image: "${SENTIMETER_SUPPORT_MIGRATION_WORKER_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__sentimeter-db: "Host=sentimeter-postgres;Port=5432;Username=postgres;Password=${SENTIMETER_POSTGRES_PASSWORD};Database=sentimeter-db"
    depends_on:
      sentimeter-postgres:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  sentimeter-ollama-data:
    driver: "local"
  sentimeter-postgres-data:
    driver: "local"
  sentimeter-identity-data:
    driver: "local"
